kind: pipeline
name: deploy production
trigger:
  branch: [develop]
  event: [push]

steps:
  - name: deploy production
    image: python:3.7
    environment:
      SSH_KEY:
        from_secret: PRIVATE_KEY
    commands:
      - pip install fabric
      - mkdir -p $HOME/.ssh/
      - echo "$SSH_KEY" > $HOME/.ssh/id_rsa
      - chmod 600 $HOME/.ssh/id_rsa
      - fab production deploy
    when:
      branch:
        - develop
      event:
        exclude:
          - pull_request

  - name: chats alert
    image: peloton/drone-google-chat

    settings:
      webhook: https://chat.googleapis.com/v1/spaces/AAAAwveY2ZM
      key: AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI
      token: SCR71sc-yLpa-WkC9Mph0t01rzEyjhOKadZJuTUc4yw%3D
      link_names: true
      template: >
        {{#success build.status}}
          {{ repo.name }} deploy {{build.number}} on deadpool.cloudez.io done with {{ since build.started }}.
        {{else}}
          {{ repo.name }} deploy {{build.number}} on deadpool.cloudez.io failed.
        {{/success}}
    when:
      branch:
        - develop
      status: [success, failure]
