version: '3'

services:
  deadpool_db:
    container_name: deadpool_db
    image: postgres:9.6
    ports:
      - '5431:5432'
    environment:
      POSTGRES_PASSWORD: deadpool
      POSTGRES_USER: deadpool
      POSTGRES_DB: deadpool
    volumes:
      - './docker/postgresql:/var/lib/postgresql/data'
